### ISSUE TITLE
Initialisation of SciView fails after updating from 0.1.6 to 0.2.0-beta-1

### ISSUE THREAD

**Issue by haesleinhuepf** [scenerygraphics/sciview#187]
Hey @skalarproduktraum ,

you may remember, we included Scenery at some point into ClearControl. I just tried updating the dependency to version 0.2.0-beta1.

I'm now getting this error message:
```
java.lang.NoClassDefFoundError: graphics/scenery/utils/SceneryJPanel
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:110)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:165)
	at clearcontrol.microscope.lightsheet.postprocessing.visualisation.instructions.SciViewInstruction.initialize(SciViewInstruction.java:57)
	at clearcontrol.microscope.lightsheet.timelapse.LightSheetTimelapse.acquire(LightSheetTimelapse.java:208)
	at clearcontrol.microscope.timelapse.TimelapseBase.loop(TimelapseBase.java:355)
	at clearcontrol.core.device.task.LoopTaskDevice.run(LoopTaskDevice.java:32)
	at clearcontrol.microscope.timelapse.TimelapseBase.run(TimelapseBase.java:301)
	at clearcontrol.core.device.task.TaskDevice.lambda$startTask$0(TaskDevice.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: graphics.scenery.utils.SceneryJPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

When calling:

```
SciViewService sciViewService = context.service( SciViewService.class );
SciView sciView = sciViewService.getOrCreateActiveSciView();
```
From: https://github.com/mpicbg-csbd/clearcontrol-lightsheet-csbd/blob/master/src/main/java/clearcontrol/microscope/lightsheet/postprocessing/visualisation/instructions/SciViewInstruction.java#L56

Is there some example code available showing how to generate a SciView instance from Java and load a volume into it?

Thanks a lot! No hurry btw.

Cheers,
Robert

**Comment by skalarproduktraum** [comment]
Hi @haesleinhuepf,

the code you have for that (and maybe a `sciView.addVolume(...)` afterwards) is essentially all you need. The error you are seeing looks to me like there's an outdated scenery version somewhere on the classpath, as `SceneryJPanel` was only introduced very recently, with 0.7.0-beta-1. Could you check that please?

**Comment by haesleinhuepf** [comment]
Hey @skalarproduktraum ,

I just set up a development environment on a new computer and tried scivew 0.2.0 again. Now, I'm getting the error message

```
Unable to load native library: no spirvcrossj in java.library.path
Did you include spirvcrossj-natives-windows in your dependencies?
```

Even though the dependency is in my pom:
```
		<dependency>
			<groupId>graphics.scenery</groupId>
			<artifactId>spirvcrossj</artifactId>
			<version>0.5.2-1.1.101.0</version>
		</dependency>
```
Is it the right version?

Thanks!

Cheers,
Robert

**Comment by skalarproduktraum** [comment]
Yes, that's the correct and most current version. It should have also downloaded native libraries for that, depending on your platform -- they have the qualifiers `-natives-windows` (or linux or macos) at the end, are they there as well?

**Comment by haesleinhuepf** [comment]
I tried this (error message on the very bottom):
![image](https://user-images.githubusercontent.com/12660498/56313500-07a5d880-6153-11e9-8b8b-df81d8965368.png)

The dependency is supposed to be like that, right?

**Comment by haesleinhuepf** [comment]
@skalarproduktraum fixed it (partly) by adding this to the VM command line:
-Dspirvcrossj.useContextClassLoader

This is a workaround. It would be nice if it could work without... ;-)

**Comment by skalarproduktraum** [comment]
Just to note, the workaround can also be done programmatically: 

Insert this before launching scenery/sciview:
```java
System.setProperty("spirvcrossj.useContextClassLoader", "true")
```
